# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: password
#   socket: /tmp/mysql.sock
#   host: db

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

development:
  <<: *default
  database: studyup_development

production:
  <<: *default
  database: studyup_production
  username: studyup
  password: <%= ENV['STUDYUP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: studyup_test
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>